# Generated by Django 6.0.1 on 2026-02-04 21:45

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NormativeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título del Documento')),
                ('document_type', models.CharField(choices=[('law', 'Ley / Regulación'), ('policy', 'Política Interna'), ('manual', 'Manual de Procedimiento'), ('other', 'Otro')], default='policy', max_length=20, verbose_name='Tipo')),
                ('file', models.FileField(upload_to='normative_docs/', verbose_name='Archivo PDF')),
                ('description', models.TextField(blank=True, verbose_name='Descripción / Alcance')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Procesado por IA')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Documento Normativo',
                'verbose_name_plural': 'Documentos Normativos',
            },
        ),
        migrations.CreateModel(
            name='HistoricalNormativeDocument',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('title', models.CharField(max_length=255, verbose_name='Título del Documento')),
                ('document_type', models.CharField(choices=[('law', 'Ley / Regulación'), ('policy', 'Política Interna'), ('manual', 'Manual de Procedimiento'), ('other', 'Otro')], default='policy', max_length=20, verbose_name='Tipo')),
                ('file', models.TextField(max_length=100, verbose_name='Archivo PDF')),
                ('description', models.TextField(blank=True, verbose_name='Descripción / Alcance')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Procesado por IA')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Documento Normativo',
                'verbose_name_plural': 'historical Documentos Normativos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('chunk_index', models.PositiveIntegerField()),
                ('text_content', models.TextField()),
                ('vector_id', models.CharField(blank=True, max_length=100, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.normativedocument')),
            ],
            options={
                'verbose_name': 'Fragmento de Documento',
                'verbose_name_plural': 'Fragmentos de Documentos',
                'ordering': ['chunk_index'],
            },
        ),
    ]
