# Generated by Django 6.0.1 on 2026-02-04 22:11

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título de la Entrevista')),
                ('date', models.DateField(verbose_name='Fecha de la Entrevista')),
                ('interviewer', models.CharField(max_length=100, verbose_name='Entrevistador')),
                ('interviewee', models.CharField(max_length=100, verbose_name='Entrevistado')),
                ('audio_file', models.FileField(upload_to='interviews/audio/', verbose_name='Archivo de Audio')),
                ('transcript', models.TextField(blank=True, verbose_name='Transcripción (Auto)')),
                ('is_transcribed', models.BooleanField(default=False, verbose_name='Transcrito')),
            ],
            options={
                'verbose_name': 'Sesión de Entrevista',
                'verbose_name_plural': 'Sesiones de Entrevistas',
            },
        ),
        migrations.CreateModel(
            name='HistoricalInterviewSession',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('title', models.CharField(max_length=255, verbose_name='Título de la Entrevista')),
                ('date', models.DateField(verbose_name='Fecha de la Entrevista')),
                ('interviewer', models.CharField(max_length=100, verbose_name='Entrevistador')),
                ('interviewee', models.CharField(max_length=100, verbose_name='Entrevistado')),
                ('audio_file', models.TextField(max_length=100, verbose_name='Archivo de Audio')),
                ('transcript', models.TextField(blank=True, verbose_name='Transcripción (Auto)')),
                ('is_transcribed', models.BooleanField(default=False, verbose_name='Transcrito')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Sesión de Entrevista',
                'verbose_name_plural': 'historical Sesiones de Entrevistas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
