# Generated by Django 6.0.1 on 2026-02-02 20:59

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('risk_universe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('control_type', models.CharField(choices=[('preventive', 'Preventivo'), ('detective', 'Detectivo'), ('corrective', 'Correctivo')], max_length=20, verbose_name='Tipo')),
                ('nature', models.CharField(choices=[('manual', 'Manual'), ('automated', 'Automático'), ('hybrid', 'Híbrido')], max_length=20, verbose_name='Naturaleza')),
                ('frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('annual', 'Anual'), ('event', 'Por Evento')], max_length=20, verbose_name='Frecuencia')),
                ('risks', models.ManyToManyField(blank=True, related_name='controls', to='risk_universe.risk', verbose_name='Riesgos Mitigados')),
            ],
            options={
                'verbose_name': 'Control',
                'verbose_name_plural': 'Controles',
            },
        ),
        migrations.CreateModel(
            name='ControlAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('assessor', models.CharField(max_length=100, verbose_name='Evaluador')),
                ('date', models.DateField(verbose_name='Fecha Evaluación')),
                ('design_effectiveness', models.CharField(choices=[('effective', 'Efectivo'), ('ineffective', 'Inefectivo'), ('needs_improvement', 'Necesita Mejora')], max_length=20, verbose_name='Efectividad Diseño')),
                ('operational_effectiveness', models.CharField(choices=[('effective', 'Efectivo'), ('ineffective', 'Inefectivo'), ('needs_improvement', 'Necesita Mejora')], max_length=20, verbose_name='Efectividad Operativa')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='controls.control', verbose_name='Control')),
            ],
            options={
                'verbose_name': 'Evaluación de Control',
                'verbose_name_plural': 'Evaluaciones de Control',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalControl',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('code', models.CharField(db_index=True, max_length=50, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('control_type', models.CharField(choices=[('preventive', 'Preventivo'), ('detective', 'Detectivo'), ('corrective', 'Correctivo')], max_length=20, verbose_name='Tipo')),
                ('nature', models.CharField(choices=[('manual', 'Manual'), ('automated', 'Automático'), ('hybrid', 'Híbrido')], max_length=20, verbose_name='Naturaleza')),
                ('frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('annual', 'Anual'), ('event', 'Por Evento')], max_length=20, verbose_name='Frecuencia')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Control',
                'verbose_name_plural': 'historical Controles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalControlAssessment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('assessor', models.CharField(max_length=100, verbose_name='Evaluador')),
                ('date', models.DateField(verbose_name='Fecha Evaluación')),
                ('design_effectiveness', models.CharField(choices=[('effective', 'Efectivo'), ('ineffective', 'Inefectivo'), ('needs_improvement', 'Necesita Mejora')], max_length=20, verbose_name='Efectividad Diseño')),
                ('operational_effectiveness', models.CharField(choices=[('effective', 'Efectivo'), ('ineffective', 'Inefectivo'), ('needs_improvement', 'Necesita Mejora')], max_length=20, verbose_name='Efectividad Operativa')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('control', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='controls.control', verbose_name='Control')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Evaluación de Control',
                'verbose_name_plural': 'historical Evaluaciones de Control',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
