# Generated by Django 6.0.1 on 2026-02-04 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0001_initial'),
        ('risk_universe', '0002_alter_risk_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control',
            options={'ordering': ['code'], 'verbose_name': 'Control', 'verbose_name_plural': 'Controles'},
        ),
        migrations.RemoveField(
            model_name='control',
            name='control_type',
        ),
        migrations.RemoveField(
            model_name='control',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='control',
            name='nature',
        ),
        migrations.RemoveField(
            model_name='historicalcontrol',
            name='control_type',
        ),
        migrations.RemoveField(
            model_name='historicalcontrol',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='historicalcontrol',
            name='nature',
        ),
        migrations.AddField(
            model_name='control',
            name='weight_formalization',
            field=models.IntegerField(choices=[(10, 'Formalizado en documento (10%)'), (5, 'No Formalizado / Informal (5%)'), (0, 'Sin Control (0%)')], default=0, verbose_name='Formalización (10%)'),
        ),
        migrations.AddField(
            model_name='control',
            name='weight_opportunity',
            field=models.IntegerField(choices=[(35, 'Preventivo (35%)'), (20, 'Detectivo (20%)'), (0, 'Sin Control (0%)')], default=0, verbose_name='Oportunidad (35%)'),
        ),
        migrations.AddField(
            model_name='control',
            name='weight_scope',
            field=models.IntegerField(choices=[(20, 'Total - 100% Operaciones (20%)'), (5, 'Parcial / Muestral (5%)'), (0, 'Sin Control (0%)')], default=0, verbose_name='Alcance (20%)'),
        ),
        migrations.AddField(
            model_name='control',
            name='weight_segregation',
            field=models.IntegerField(choices=[(15, 'Sí - Funciones separadas (15%)'), (0, 'No - Misma función ejecuta y controla (0%)')], default=0, verbose_name='Segregación (15%)'),
        ),
        migrations.AddField(
            model_name='control',
            name='weight_type',
            field=models.IntegerField(choices=[(20, 'Automático (20%)'), (15, 'Semiautomático (15%)'), (5, 'Manual (5%)'), (0, 'Sin Control (0%)')], default=0, verbose_name='Tipo (20%)'),
        ),
        migrations.AddField(
            model_name='historicalcontrol',
            name='weight_formalization',
            field=models.IntegerField(choices=[(10, 'Formalizado en documento (10%)'), (5, 'No Formalizado / Informal (5%)'), (0, 'Sin Control (0%)')], default=0, verbose_name='Formalización (10%)'),
        ),
        migrations.AddField(
            model_name='historicalcontrol',
            name='weight_opportunity',
            field=models.IntegerField(choices=[(35, 'Preventivo (35%)'), (20, 'Detectivo (20%)'), (0, 'Sin Control (0%)')], default=0, verbose_name='Oportunidad (35%)'),
        ),
        migrations.AddField(
            model_name='historicalcontrol',
            name='weight_scope',
            field=models.IntegerField(choices=[(20, 'Total - 100% Operaciones (20%)'), (5, 'Parcial / Muestral (5%)'), (0, 'Sin Control (0%)')], default=0, verbose_name='Alcance (20%)'),
        ),
        migrations.AddField(
            model_name='historicalcontrol',
            name='weight_segregation',
            field=models.IntegerField(choices=[(15, 'Sí - Funciones separadas (15%)'), (0, 'No - Misma función ejecuta y controla (0%)')], default=0, verbose_name='Segregación (15%)'),
        ),
        migrations.AddField(
            model_name='historicalcontrol',
            name='weight_type',
            field=models.IntegerField(choices=[(20, 'Automático (20%)'), (15, 'Semiautomático (15%)'), (5, 'Manual (5%)'), (0, 'Sin Control (0%)')], default=0, verbose_name='Tipo (20%)'),
        ),
        migrations.AlterField(
            model_name='control',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='control',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='control',
            name='risks',
            field=models.ManyToManyField(blank=True, related_name='controls', to='risk_universe.risk'),
        ),
        migrations.AlterField(
            model_name='controlassessment',
            name='assessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='controlassessment',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='controls.control'),
        ),
        migrations.AlterField(
            model_name='controlassessment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='controlassessment',
            name='design_effectiveness',
            field=models.CharField(choices=[('Effective', 'Effective'), ('Ineffective', 'Ineffective')], max_length=20),
        ),
        migrations.AlterField(
            model_name='controlassessment',
            name='observations',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='controlassessment',
            name='operational_effectiveness',
            field=models.CharField(choices=[('Effective', 'Effective'), ('Ineffective', 'Ineffective')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcontrol',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcontrol',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historicalcontrol',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalcontrolassessment',
            name='assessor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalcontrolassessment',
            name='control',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='controls.control'),
        ),
        migrations.AlterField(
            model_name='historicalcontrolassessment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historicalcontrolassessment',
            name='design_effectiveness',
            field=models.CharField(choices=[('Effective', 'Effective'), ('Ineffective', 'Ineffective')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcontrolassessment',
            name='observations',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalcontrolassessment',
            name='operational_effectiveness',
            field=models.CharField(choices=[('Effective', 'Effective'), ('Ineffective', 'Ineffective')], max_length=20),
        ),
    ]
