# Generated by Django 6.0.1 on 2026-02-04 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodology', '0001_initial'),
        ('risk_universe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='risk',
            options={'ordering': ['-created'], 'verbose_name': 'Riesgo', 'verbose_name_plural': 'Riesgos'},
        ),
        migrations.RemoveField(
            model_name='historicalrisk',
            name='inherent_impact',
        ),
        migrations.RemoveField(
            model_name='historicalrisk',
            name='residual_impact',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='inherent_impact',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='residual_impact',
        ),
        migrations.AddField(
            model_name='historicalrisk',
            name='inherent_impact_level',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Nivel Impacto Inherente (1-5)'),
        ),
        migrations.AddField(
            model_name='historicalrisk',
            name='residual_impact_level',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Nivel Impacto Residual (1-5)'),
        ),
        migrations.AddField(
            model_name='risk',
            name='inherent_impact_level',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Nivel Impacto Inherente (1-5)'),
        ),
        migrations.AddField(
            model_name='risk',
            name='residual_impact_level',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Nivel Impacto Residual (1-5)'),
        ),
        migrations.AlterField(
            model_name='historicalrisk',
            name='inherent_probability',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='methodology.probabilityscale', verbose_name='Probabilidad Inherente'),
        ),
        migrations.AlterField(
            model_name='historicalrisk',
            name='residual_probability',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='methodology.probabilityscale', verbose_name='Probabilidad Residual'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='inherent_probability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inherent_risks', to='methodology.probabilityscale', verbose_name='Probabilidad Inherente'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='residual_probability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='residual_risks', to='methodology.probabilityscale', verbose_name='Probabilidad Residual'),
        ),
    ]
