# Generated by Django 6.0.1 on 2026-02-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_universe', '0002_alter_risk_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrisk',
            name='code',
            field=models.CharField(db_index=True, default='R-NEW', max_length=20, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='risk',
            name='code',
            field=models.CharField(default='R-NEW', max_length=20, unique=True, verbose_name='Código'),
        ),
    ]
