# Generated by Django 6.0.1 on 2026-02-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_universe', '0003_historicalrisk_code_risk_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrisk',
            name='inherent_impact_level',
        ),
        migrations.RemoveField(
            model_name='historicalrisk',
            name='residual_impact_level',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='inherent_impact_level',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='residual_impact_level',
        ),
        migrations.AddField(
            model_name='historicalrisk',
            name='ai_context',
            field=models.TextField(blank=True, help_text='Información capturada por la IA para sugerir este riesgo.', verbose_name='Contexto IA/Entrevista'),
        ),
        migrations.AddField(
            model_name='historicalrisk',
            name='impact_financial',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Impacto Financiero (1-5)'),
        ),
        migrations.AddField(
            model_name='historicalrisk',
            name='impact_operational',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Impacto Continuidad Operativa (1-5)'),
        ),
        migrations.AddField(
            model_name='historicalrisk',
            name='impact_people',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Impacto Personas (1-5)'),
        ),
        migrations.AddField(
            model_name='historicalrisk',
            name='impact_regulatory',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Impacto Legal/Regulatorio (1-5)'),
        ),
        migrations.AddField(
            model_name='historicalrisk',
            name='impact_reputational',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Impacto Reputacional (1-5)'),
        ),
        migrations.AddField(
            model_name='risk',
            name='ai_context',
            field=models.TextField(blank=True, help_text='Información capturada por la IA para sugerir este riesgo.', verbose_name='Contexto IA/Entrevista'),
        ),
        migrations.AddField(
            model_name='risk',
            name='impact_financial',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Impacto Financiero (1-5)'),
        ),
        migrations.AddField(
            model_name='risk',
            name='impact_operational',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Impacto Continuidad Operativa (1-5)'),
        ),
        migrations.AddField(
            model_name='risk',
            name='impact_people',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Impacto Personas (1-5)'),
        ),
        migrations.AddField(
            model_name='risk',
            name='impact_regulatory',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Impacto Legal/Regulatorio (1-5)'),
        ),
        migrations.AddField(
            model_name='risk',
            name='impact_reputational',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Impacto Reputacional (1-5)'),
        ),
    ]
