# Generated by Django 6.0.1 on 2026-02-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_universe', '0004_remove_historicalrisk_inherent_impact_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrisk',
            name='antecedent',
            field=models.TextField(blank=True, verbose_name='Antecedente de Riesgo'),
        ),
        migrations.AddField(
            model_name='risk',
            name='antecedent',
            field=models.TextField(blank=True, verbose_name='Antecedente de Riesgo'),
        ),
    ]
