# Generated by Django 6.0.1 on 2026-02-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_universe', '0005_historicalrisk_antecedent_risk_antecedent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrisk',
            name='impact_financial',
        ),
        migrations.RemoveField(
            model_name='historicalrisk',
            name='impact_operational',
        ),
        migrations.RemoveField(
            model_name='historicalrisk',
            name='impact_people',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='impact_financial',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='impact_operational',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='impact_people',
        ),
        migrations.AddField(
            model_name='historicalrisk',
            name='impact_clients',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Impacto Clientes (1-5)'),
        ),
        migrations.AddField(
            model_name='historicalrisk',
            name='impact_monetary',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Impacto Monetario (1-5)'),
        ),
        migrations.AddField(
            model_name='historicalrisk',
            name='impact_processes',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Impacto Procesos (1-5)'),
        ),
        migrations.AddField(
            model_name='risk',
            name='impact_clients',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Impacto Clientes (1-5)'),
        ),
        migrations.AddField(
            model_name='risk',
            name='impact_monetary',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Impacto Monetario (1-5)'),
        ),
        migrations.AddField(
            model_name='risk',
            name='impact_processes',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Impacto Procesos (1-5)'),
        ),
        migrations.AlterField(
            model_name='historicalrisk',
            name='impact_regulatory',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Impacto Normativo (1-5)'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='impact_regulatory',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Impacto Normativo (1-5)'),
        ),
    ]
