# Generated by Django 6.0.1 on 2026-02-05 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_universe', '0006_remove_historicalrisk_impact_financial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='risk_universe.process', verbose_name='Proceso'),
        ),
    ]
