# Generated by Django 6.0.1 on 2026-02-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_universe', '0007_alter_risk_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocess',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='process',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
