# Generated by Django 6.0.1 on 2026-02-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_universe', '0008_historicalprocess_is_active_process_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocess',
            name='analyst',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Analista Asignado'),
        ),
        migrations.AddField(
            model_name='process',
            name='analyst',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Analista Asignado'),
        ),
        migrations.AlterField(
            model_name='historicalprocess',
            name='owner',
            field=models.CharField(max_length=100, verbose_name='Dueño del Proceso (Entrevistado)'),
        ),
        migrations.AlterField(
            model_name='historicalrisk',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='process',
            name='owner',
            field=models.CharField(max_length=100, verbose_name='Dueño del Proceso (Entrevistado)'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código'),
        ),
    ]
