# Generated by Django 6.0.1 on 2026-02-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_universe', '0009_historicalprocess_analyst_process_analyst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrisk',
            name='etapas_actividades',
            field=models.TextField(blank=True, verbose_name='Etapas o Actividades'),
        ),
        migrations.AddField(
            model_name='historicalrisk',
            name='factor_riesgo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Factor de Riesgo'),
        ),
        migrations.AddField(
            model_name='historicalrisk',
            name='factor_riesgo_especifico',
            field=models.CharField(blank=True, max_length=200, verbose_name='Factor de Riesgo Específico'),
        ),
        migrations.AddField(
            model_name='historicalrisk',
            name='requiere_indicador',
            field=models.BooleanField(default=False, verbose_name='Requiere indicador'),
        ),
        migrations.AddField(
            model_name='historicalrisk',
            name='requiere_plan_accion',
            field=models.BooleanField(default=False, verbose_name='Requiere plan de acción'),
        ),
        migrations.AddField(
            model_name='historicalrisk',
            name='tipos_perdida_basilea',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tipos de Pérdida Basilea'),
        ),
        migrations.AddField(
            model_name='risk',
            name='etapas_actividades',
            field=models.TextField(blank=True, verbose_name='Etapas o Actividades'),
        ),
        migrations.AddField(
            model_name='risk',
            name='factor_riesgo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Factor de Riesgo'),
        ),
        migrations.AddField(
            model_name='risk',
            name='factor_riesgo_especifico',
            field=models.CharField(blank=True, max_length=200, verbose_name='Factor de Riesgo Específico'),
        ),
        migrations.AddField(
            model_name='risk',
            name='requiere_indicador',
            field=models.BooleanField(default=False, verbose_name='Requiere indicador'),
        ),
        migrations.AddField(
            model_name='risk',
            name='requiere_plan_accion',
            field=models.BooleanField(default=False, verbose_name='Requiere plan de acción'),
        ),
        migrations.AddField(
            model_name='risk',
            name='tipos_perdida_basilea',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tipos de Pérdida Basilea'),
        ),
        migrations.AlterField(
            model_name='historicalprocess',
            name='owner',
            field=models.CharField(max_length=100, verbose_name='Dueño del Proceso'),
        ),
        migrations.AlterField(
            model_name='historicalrisk',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Riesgos de Pérdida'),
        ),
        migrations.AlterField(
            model_name='process',
            name='owner',
            field=models.CharField(max_length=100, verbose_name='Dueño del Proceso'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Riesgos de Pérdida'),
        ),
    ]
