# Generated by Django 6.0.1 on 2026-02-07 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodology', '0001_initial'),
        ('risk_universe', '0010_historicalrisk_etapas_actividades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrisk',
            name='inherent_probability',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='methodology.probabilityscale', verbose_name='Probabilidad'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='inherent_probability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inherent_risks', to='methodology.probabilityscale', verbose_name='Probabilidad'),
        ),
    ]
