# Generated by Django 6.0.1 on 2026-02-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_universe', '0011_alter_historicalrisk_inherent_probability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrisk',
            name='inherent_impact_level',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Nivel de Impacto Inherente (1-5)'),
        ),
        migrations.AddField(
            model_name='historicalrisk',
            name='inherent_risk_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Riesgo Inherente'),
        ),
        migrations.AddField(
            model_name='historicalrisk',
            name='manual_inherent_override',
            field=models.BooleanField(default=False, verbose_name='Cálculo Manual'),
        ),
        migrations.AddField(
            model_name='historicalrisk',
            name='manual_residual_override',
            field=models.BooleanField(default=False, verbose_name='Cálculo Manual'),
        ),
        migrations.AddField(
            model_name='historicalrisk',
            name='residual_impact_level',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Nivel de Impacto Residual (1-5)'),
        ),
        migrations.AddField(
            model_name='historicalrisk',
            name='residual_risk_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Riesgo Residual'),
        ),
        migrations.AddField(
            model_name='risk',
            name='inherent_impact_level',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Nivel de Impacto Inherente (1-5)'),
        ),
        migrations.AddField(
            model_name='risk',
            name='inherent_risk_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Riesgo Inherente'),
        ),
        migrations.AddField(
            model_name='risk',
            name='manual_inherent_override',
            field=models.BooleanField(default=False, verbose_name='Cálculo Manual'),
        ),
        migrations.AddField(
            model_name='risk',
            name='manual_residual_override',
            field=models.BooleanField(default=False, verbose_name='Cálculo Manual'),
        ),
        migrations.AddField(
            model_name='risk',
            name='residual_impact_level',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Nivel de Impacto Residual (1-5)'),
        ),
        migrations.AddField(
            model_name='risk',
            name='residual_risk_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Riesgo Residual'),
        ),
        migrations.AlterField(
            model_name='historicalrisk',
            name='impact_clients',
            field=models.PositiveIntegerField(choices=[(1, 'Bajo'), (2, 'Medio Bajo'), (3, 'Medio'), (4, 'Medio Alto'), (5, 'Alto')], default=1, verbose_name='Clientes'),
        ),
        migrations.AlterField(
            model_name='historicalrisk',
            name='impact_monetary',
            field=models.PositiveIntegerField(choices=[(1, 'Bajo'), (2, 'Medio Bajo'), (3, 'Medio'), (4, 'Medio Alto'), (5, 'Alto')], default=1, verbose_name='Monetario'),
        ),
        migrations.AlterField(
            model_name='historicalrisk',
            name='impact_processes',
            field=models.PositiveIntegerField(choices=[(1, 'Bajo'), (2, 'Medio Bajo'), (3, 'Medio'), (4, 'Medio Alto'), (5, 'Alto')], default=1, verbose_name='Procesos'),
        ),
        migrations.AlterField(
            model_name='historicalrisk',
            name='impact_regulatory',
            field=models.PositiveIntegerField(choices=[(1, 'Bajo'), (2, 'Medio Bajo'), (3, 'Medio'), (4, 'Medio Alto'), (5, 'Alto')], default=1, verbose_name='Normativo'),
        ),
        migrations.AlterField(
            model_name='historicalrisk',
            name='impact_reputational',
            field=models.PositiveIntegerField(choices=[(1, 'Bajo'), (2, 'Medio Bajo'), (3, 'Medio'), (4, 'Medio Alto'), (5, 'Alto')], default=1, verbose_name='Reputacional'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='impact_clients',
            field=models.PositiveIntegerField(choices=[(1, 'Bajo'), (2, 'Medio Bajo'), (3, 'Medio'), (4, 'Medio Alto'), (5, 'Alto')], default=1, verbose_name='Clientes'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='impact_monetary',
            field=models.PositiveIntegerField(choices=[(1, 'Bajo'), (2, 'Medio Bajo'), (3, 'Medio'), (4, 'Medio Alto'), (5, 'Alto')], default=1, verbose_name='Monetario'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='impact_processes',
            field=models.PositiveIntegerField(choices=[(1, 'Bajo'), (2, 'Medio Bajo'), (3, 'Medio'), (4, 'Medio Alto'), (5, 'Alto')], default=1, verbose_name='Procesos'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='impact_regulatory',
            field=models.PositiveIntegerField(choices=[(1, 'Bajo'), (2, 'Medio Bajo'), (3, 'Medio'), (4, 'Medio Alto'), (5, 'Alto')], default=1, verbose_name='Normativo'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='impact_reputational',
            field=models.PositiveIntegerField(choices=[(1, 'Bajo'), (2, 'Medio Bajo'), (3, 'Medio'), (4, 'Medio Alto'), (5, 'Alto')], default=1, verbose_name='Reputacional'),
        ),
    ]
