# Generated by Django 6.0.1 on 2026-02-13 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
        ('risk_universe', '0012_historicalrisk_inherent_impact_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrisk',
            name='tipos_perdida_basilea',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='tipos_perdida_basilea',
        ),
        migrations.AddField(
            model_name='historicalrisk',
            name='basilea_loss_type',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'config_list__technical_name': 'basilea_loss_type'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configurations.configlistitem', verbose_name='Tipo de Pérdida Basilea (Lista)'),
        ),
        migrations.AddField(
            model_name='historicalrisk',
            name='loss_risk_type',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'config_list__technical_name': 'loss_risk_type'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configurations.configlistitem', verbose_name='Riesgos de Pérdida (Lista)'),
        ),
        migrations.AddField(
            model_name='historicalrisk',
            name='risk_factor',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'config_list__technical_name': 'risk_factor'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configurations.configlistitem', verbose_name='Factor de Riesgo (Lista)'),
        ),
        migrations.AddField(
            model_name='risk',
            name='basilea_loss_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'config_list__technical_name': 'basilea_loss_type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks_basilea', to='configurations.configlistitem', verbose_name='Tipo de Pérdida Basilea (Lista)'),
        ),
        migrations.AddField(
            model_name='risk',
            name='loss_risk_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'config_list__technical_name': 'loss_risk_type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks_loss_type', to='configurations.configlistitem', verbose_name='Riesgos de Pérdida (Lista)'),
        ),
        migrations.AddField(
            model_name='risk',
            name='risk_factor',
            field=models.ForeignKey(blank=True, limit_choices_to={'config_list__technical_name': 'risk_factor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks_factor', to='configurations.configlistitem', verbose_name='Factor de Riesgo (Lista)'),
        ),
        migrations.AlterField(
            model_name='historicalrisk',
            name='factor_riesgo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Factor de Riesgo (Legacy)'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='factor_riesgo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Factor de Riesgo (Legacy)'),
        ),
    ]
