# Generated by Django 6.0.1 on 2026-02-13 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0004_seed_exact_lists_v2'),
        ('risk_universe', '0013_remove_historicalrisk_tipos_perdida_basilea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrisk',
            name='basilea_loss_type',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'config_list__technical_name': 'tipos_perdida_basilea'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configurations.configlistitem', verbose_name='Tipo de Pérdida Basilea (Lista)'),
        ),
        migrations.AlterField(
            model_name='historicalrisk',
            name='loss_risk_type',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'config_list__technical_name': 'riesgos_de_perdida'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configurations.configlistitem', verbose_name='Riesgos de Pérdida (Lista)'),
        ),
        migrations.AlterField(
            model_name='historicalrisk',
            name='risk_factor',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'config_list__technical_name': 'factor_de_riesgo'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configurations.configlistitem', verbose_name='Factor de Riesgo (Lista)'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='basilea_loss_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'config_list__technical_name': 'tipos_perdida_basilea'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks_basilea', to='configurations.configlistitem', verbose_name='Tipo de Pérdida Basilea (Lista)'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='loss_risk_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'config_list__technical_name': 'riesgos_de_perdida'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks_loss_type', to='configurations.configlistitem', verbose_name='Riesgos de Pérdida (Lista)'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='risk_factor',
            field=models.ForeignKey(blank=True, limit_choices_to={'config_list__technical_name': 'factor_de_riesgo'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks_factor', to='configurations.configlistitem', verbose_name='Factor de Riesgo (Lista)'),
        ),
    ]
