# Generated by Django 6.0.1 on 2026-02-14 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0005_alter_control_alcance_control_and_more'),
        ('risk_universe', '0014_alter_historicalrisk_basilea_loss_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrisk',
            name='control_principal',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='controls.control', verbose_name='Control Principal'),
        ),
        migrations.AddField(
            model_name='risk',
            name='control_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal_risks', to='controls.control', verbose_name='Control Principal'),
        ),
    ]
