# Generated by Django 6.0.1 on 2026-02-14 16:58

import django.db.models.deletion
from django.db import migrations, models


def migrate_control_risk_links(apps, schema_editor):
    RiskControlLink = apps.get_model('risk_universe', 'RiskControlLink')
    Risk = apps.get_model('risk_universe', 'Risk')
    Control = apps.get_model('controls', 'Control')
    
    # We use raw SQL because the old table might not be accessible via models
    # if it's already "removed" from the model definition.
    # But since we changed dependencies, 'controls_control_risks' should still exist.
    from django.db import connection
    with connection.cursor() as cursor:
        # Check if old table exists
        cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='controls_control_risks'")
        if cursor.fetchone():
            cursor.execute("SELECT control_id, risk_id FROM controls_control_risks")
            for control_id, risk_id in cursor.fetchall():
                try:
                    # Verify IDs exist in case of orphan data
                    if Risk.objects.filter(id=risk_id).exists() and Control.objects.filter(id=control_id).exists():
                        RiskControlLink.objects.get_or_create(risk_id=risk_id, control_id=control_id)
                except Exception as e:
                    print(f"Error migrating link {control_id}-{risk_id}: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0005_alter_control_alcance_control_and_more'),
        ('risk_universe', '0015_historicalrisk_control_principal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskControlLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_links', to='controls.control')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_links', to='risk_universe.risk')),
            ],
            options={
                'verbose_name': 'Vínculo de Control',
                'verbose_name_plural': 'Vínculos de Controles',
                'unique_together': {('risk', 'control')},
            },
        ),
        migrations.AddField(
            model_name='risk',
            name='controls',
            field=models.ManyToManyField(blank=True, related_name='risks_linked', through='risk_universe.RiskControlLink', to='controls.control', verbose_name='Controles Vinculados'),
        ),
        migrations.RunPython(migrate_control_risk_links),
    ]
