# Generated by Django 6.0.1 on 2026-02-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_universe', '0016_riskcontrollink_risk_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrisk',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='risk',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
