# Generated by Django 6.0.1 on 2026-02-14 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_universe', '0017_historicalrisk_is_active_risk_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrisk',
            name='manual_inherent_override',
        ),
        migrations.RemoveField(
            model_name='historicalrisk',
            name='manual_residual_override',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='manual_inherent_override',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='manual_residual_override',
        ),
    ]
