# Generated by Django 6.0.1 on 2026-02-15 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_universe', '0018_remove_historicalrisk_manual_inherent_override_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrisk',
            name='control_principal',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='control_principal',
        ),
        migrations.AddField(
            model_name='historicalrisk',
            name='is_factor_riesgo_especifico_ai_suggested',
            field=models.BooleanField(default=False, verbose_name='Sugerido por IA'),
        ),
        migrations.AddField(
            model_name='historicalrisk',
            name='is_factor_riesgo_especifico_overridden',
            field=models.BooleanField(default=False, verbose_name='Editado manualmente'),
        ),
        migrations.AddField(
            model_name='historicalrisk',
            name='responsible_analyst',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Analista Responsable'),
        ),
        migrations.AddField(
            model_name='historicalrisk',
            name='risk_owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Dueño del Riesgo'),
        ),
        migrations.AddField(
            model_name='risk',
            name='is_factor_riesgo_especifico_ai_suggested',
            field=models.BooleanField(default=False, verbose_name='Sugerido por IA'),
        ),
        migrations.AddField(
            model_name='risk',
            name='is_factor_riesgo_especifico_overridden',
            field=models.BooleanField(default=False, verbose_name='Editado manualmente'),
        ),
        migrations.AddField(
            model_name='risk',
            name='responsible_analyst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks_as_analyst', to=settings.AUTH_USER_MODEL, verbose_name='Analista Responsable'),
        ),
        migrations.AddField(
            model_name='risk',
            name='risk_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks_as_owner', to=settings.AUTH_USER_MODEL, verbose_name='Dueño del Riesgo'),
        ),
    ]
