# Generated by Django 6.0.1 on 2026-02-15 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_universe', '0019_remove_historicalrisk_control_principal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('area', models.CharField(blank=True, max_length=150, verbose_name='Área / Cargo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Dueño de Riesgo',
                'verbose_name_plural': 'Catálogo de Dueños',
            },
        ),
        migrations.AlterField(
            model_name='historicalrisk',
            name='risk_owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='risk_universe.riskowner', verbose_name='Dueño del Riesgo'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='risk_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks_as_owner', to='risk_universe.riskowner', verbose_name='Dueño del Riesgo'),
        ),
    ]
