# Generated by Django 6.0.1 on 2026-02-15 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_universe', '0020_riskowner_alter_historicalrisk_risk_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprocess',
            name='owner',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dueño del Proceso (Temp)'),
        ),
        migrations.AlterField(
            model_name='process',
            name='owner',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dueño del Proceso (Temp)'),
        ),
    ]
