# Generated by Django 6.0.1 on 2026-02-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_universe', '0021_alter_historicalprocess_owner_alter_process_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprocess',
            name='owner',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dueño del Proceso (Temp)'),
        ),
        migrations.AlterField(
            model_name='process',
            name='owner',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dueño del Proceso (Temp)'),
        ),
    ]
