# Generated by Django 6.0.1 on 2026-02-15 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_universe', '0022_alter_historicalprocess_owner_alter_process_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprocess',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='risk_universe.riskowner', verbose_name='Dueño del Proceso'),
        ),
        migrations.AlterField(
            model_name='process',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes_owned', to='risk_universe.riskowner', verbose_name='Dueño del Proceso'),
        ),
    ]
