# Generated by Django 6.0.1 on 2026-02-15 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0008_controlassessment_is_active_and_more'),
        ('risk_universe', '0023_alter_historicalprocess_owner_alter_process_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrisk',
            name='control_principal',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='controls.control', verbose_name='Control Principal'),
        ),
        migrations.AddField(
            model_name='risk',
            name='control_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal_risks', to='controls.control', verbose_name='Control Principal'),
        ),
    ]
