# Generated by Django 6.0.1 on 2026-02-02 21:01

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controls', '0001_initial'),
        ('risk_universe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(verbose_name='Descripción de la Acción')),
                ('responsible', models.CharField(max_length=100, verbose_name='Responsable')),
                ('due_date', models.DateField(verbose_name='Fecha Vencimiento')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('verified', 'Verificado'), ('closed', 'Cerrado'), ('overdue', 'Vencido')], default='pending', max_length=20, verbose_name='Estado')),
                ('control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to='controls.control', verbose_name='Control')),
                ('risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to='risk_universe.risk', verbose_name='Riesgo')),
            ],
            options={
                'verbose_name': 'Plan de Acción',
                'verbose_name_plural': 'Planes de Acción',
            },
        ),
        migrations.CreateModel(
            name='HistoricalActionPlan',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('description', models.TextField(verbose_name='Descripción de la Acción')),
                ('responsible', models.CharField(max_length=100, verbose_name='Responsable')),
                ('due_date', models.DateField(verbose_name='Fecha Vencimiento')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('verified', 'Verificado'), ('closed', 'Cerrado'), ('overdue', 'Vencido')], default='pending', max_length=20, verbose_name='Estado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('control', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='controls.control', verbose_name='Control')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='risk_universe.risk', verbose_name='Riesgo')),
            ],
            options={
                'verbose_name': 'historical Plan de Acción',
                'verbose_name_plural': 'historical Planes de Acción',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalKRI',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Indicador')),
                ('description', models.TextField(verbose_name='Descripción/Fórmula')),
                ('threshold_green', models.FloatField(verbose_name='Umbral Verde (<=)')),
                ('threshold_yellow', models.FloatField(verbose_name='Umbral Amarillo (<=)')),
                ('threshold_red', models.FloatField(verbose_name='Umbral Rojo (>)')),
                ('current_value', models.FloatField(blank=True, null=True, verbose_name='Valor Actual')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='risk_universe.risk', verbose_name='Riesgo Asociado')),
            ],
            options={
                'verbose_name': 'historical KRI',
                'verbose_name_plural': 'historical KRIs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRiskEvent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('event_type', models.CharField(choices=[('incident', 'Incidente (Sin Pérdida)'), ('loss', 'Evento de Pérdida'), ('near_miss', 'Near Miss')], max_length=20, verbose_name='Tipo de Evento')),
                ('date_occurrence', models.DateField(verbose_name='Fecha de Ocurrencia')),
                ('date_discovery', models.DateField(verbose_name='Fecha de Descubrimiento')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto Pérdida')),
                ('description', models.TextField(verbose_name='Descripción del Evento')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='risk_universe.risk', verbose_name='Riesgo Materializado')),
            ],
            options={
                'verbose_name': 'historical Evento/Incidente',
                'verbose_name_plural': 'historical Eventos e Incidentes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='KRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Indicador')),
                ('description', models.TextField(verbose_name='Descripción/Fórmula')),
                ('threshold_green', models.FloatField(verbose_name='Umbral Verde (<=)')),
                ('threshold_yellow', models.FloatField(verbose_name='Umbral Amarillo (<=)')),
                ('threshold_red', models.FloatField(verbose_name='Umbral Rojo (>)')),
                ('current_value', models.FloatField(blank=True, null=True, verbose_name='Valor Actual')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kris', to='risk_universe.risk', verbose_name='Riesgo Asociado')),
            ],
            options={
                'verbose_name': 'KRI',
                'verbose_name_plural': 'KRIs',
            },
        ),
        migrations.CreateModel(
            name='RiskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('incident', 'Incidente (Sin Pérdida)'), ('loss', 'Evento de Pérdida'), ('near_miss', 'Near Miss')], max_length=20, verbose_name='Tipo de Evento')),
                ('date_occurrence', models.DateField(verbose_name='Fecha de Ocurrencia')),
                ('date_discovery', models.DateField(verbose_name='Fecha de Descubrimiento')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto Pérdida')),
                ('description', models.TextField(verbose_name='Descripción del Evento')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='risk_universe.risk', verbose_name='Riesgo Materializado')),
            ],
            options={
                'verbose_name': 'Evento/Incidente',
                'verbose_name_plural': 'Eventos e Incidentes',
            },
        ),
    ]
