# Generated by Django 6.0.1 on 2026-02-13 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('technical_name', models.CharField(max_length=100, unique=True, verbose_name='Nombre Técnico')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Lista')),
            ],
            options={
                'verbose_name': 'Lista Maestra',
                'verbose_name_plural': 'Listas Maestras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConfigListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('technical_name', models.CharField(max_length=100, verbose_name='Nombre Técnico')),
                ('label', models.CharField(max_length=200, verbose_name='Etiqueta Visual')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('config_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='configurations.configlist', verbose_name='Lista')),
            ],
            options={
                'verbose_name': 'Ítem de Lista',
                'verbose_name_plural': 'Ítems de Lista',
                'ordering': ['config_list', 'order', 'label'],
                'unique_together': {('config_list', 'technical_name')},
            },
        ),
    ]
