# Generated by Django 6.0.1 on 2026-02-13 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_populate_lists'),
        ('risk_universe', '0013_remove_historicalrisk_tipos_perdida_basilea_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(max_length=100, verbose_name='Campo')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptado'), ('overridden', 'Ignorado/Manual')], default='pending', max_length=20, verbose_name='Estado')),
                ('recommended_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.configlistitem', verbose_name='Valor Recomendado')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='risk_universe.risk')),
            ],
            options={
                'verbose_name': 'Recomendación de Campo',
                'verbose_name_plural': 'Recomendaciones de Campos',
                'unique_together': {('risk', 'field_name')},
            },
        ),
    ]
