# Generated by Django 6.0.1 on 2026-02-14 15:40

from django.db import migrations


import re

def clean_labels(apps, schema_editor):
    ConfigListItem = apps.get_model('configurations', 'ConfigListItem')
    regex = re.compile(r'^\[[^\]]+\]\s*')
    
    for item in ConfigListItem.objects.all():
        if regex.match(item.label):
            new_label = regex.sub('', item.label)
            item.label = new_label
            item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0004_seed_exact_lists_v2'),
    ]

    operations = [
        migrations.RunPython(clean_labels, migrations.RunPython.noop),
    ]
