# Generated by Django 6.0.1 on 2026-02-14 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0005_clean_list_item_labels'),
        ('controls', '0005_alter_control_alcance_control_and_more'),
        ('risk_universe', '0014_alter_historicalrisk_basilea_loss_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldrecommendation',
            name='status',
            field=models.CharField(choices=[('recommended', 'Recomendado'), ('accepted', 'Aceptado'), ('overridden', 'Manual/Anulado'), ('dismissed', 'Descartado')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='ControlRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('recommended', 'Recomendado'), ('accepted', 'Aceptado'), ('overridden', 'Manual/Anulado'), ('dismissed', 'Descartado')], default='recommended', max_length=20, verbose_name='Estado')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controls.control', verbose_name='Control Recomendado')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_recommendations', to='risk_universe.risk')),
            ],
            options={
                'verbose_name': 'Recomendación de Control',
                'verbose_name_plural': 'Recomendaciones de Controles',
                'unique_together': {('risk', 'control')},
            },
        ),
    ]
