# Generated by Django 6.0.1 on 2026-02-14 16:07

from django.db import migrations


import re

def clean_labels(apps, schema_editor):
    ConfigListItem = apps.get_model('configurations', 'ConfigListItem')
    # Regex to catch prefixes like "1. ", "A. ", "1) ", "B) "
    # Specifically looking for 1-2 chars followed by . or ) and then space
    prefix_regex = re.compile(r'^([0-9a-zA-Z]{1,2}[.)]\s+)(.*)')
    
    for item in ConfigListItem.objects.all():
        match = prefix_regex.match(item.label)
        if match:
            new_label = match.group(2)
            item.label = new_label
            item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0006_alter_fieldrecommendation_status_and_more'),
    ]

    operations = [
        migrations.RunPython(clean_labels),
    ]
