# Generated by Django 6.0.1 on 2026-02-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0007_clean_config_list_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldrecommendation',
            name='status',
            field=models.CharField(choices=[('recommended', 'Recomendado'), ('accepted', 'Aceptado'), ('overridden', 'Manual/Anulado'), ('dismissed', 'Descartado')], default='recommended', max_length=20, verbose_name='Estado'),
        ),
    ]
